### ISSUE TITLE
Testat 0x02 am 18.01.17

### ISSUE THREAD

**Issue by cookiengineer** [INT-WAW/Slides#13]
Das erste Testat findet am 18.01.17 statt, im gleichen Raum wie immer (A008).

Da wir diese Woche zwei Mal zur Verfuegung haben, koennt ihr am Mittwoch voraussichtlich durchgehend am Projekt arbeiten. **Nutzt die Zeit am Mittwoch um auch Fragen zu stellen!**

**Testat am 18.01.17**

Beginn ist wie gehabt, mit offenem Ende. Wer spaeter keine Zeit hat, bitte am gleichen Tag einfach vorher melden damit ich die Gruppenreihenfolge entsprechend sortieren kann. Sonst Pech gehabt. Erfahrungsstand von vorherigem Semester ist, dass die Testate bis ca. 19:00 dauern koennen.

Es gibt zwei Teile: Praxis und Theorie, jeweils mit 50% / 50% bewertet.

Praxisteil setzt voraus, dass ihr einen Pull-Request gemacht habt und diesen hier verlinkt - mit dem aktuellen Stand eures Projekts. Dies ist **bis zum Montag davor 12:00Uhr** zu erledigen, da ich ansonsten die Projekte nicht ansehen kann und dementsprechend gibt's dann keine oder weniger Punkte.

Theorieteil besteht aus den behandelten Themen, mit Fokus auf Verstaendnis von ES6 und projektionsbasierter Datenverarbeitung inklusive Asynchronitaet und Networking. Es wird auch geprueft, ob ihr die Datenstrukturen synchron gehalten habt zu dem aktuellen Datenbestand und ob die Reports asynchron und parallel zur Verarbeitung abgebaut werden koennen.

**WICHTIG**

- [ ] Nehmt die eslintrc aus dem Boilerplate / master branch. Das heisst [diese Datei hier](https://github.com/INT-WAW/Boilerplate/blob/master/.eslintrc)
- [ ] Der Code muss mit eslint beautified werden und durchlaufen. (Hint: Google eslint fix)
- [ ] Die Applikation muss mit nwjs gebundlet sein.
- [ ] Die Crypto API wird auf CLIENTseite verwendet, NICHT auf Serverseite.
- [ ] Angegebener Token ist euer Teamname. Denkt euch was aus :)
- [ ] PULL REQUEST auf die Boilerplate

**Comment by 1520152NPHSM** [comment]
Gruppenname: Die Dudes
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/44

**Comment by marioschmidt4** [comment]
Gruppenname: imo
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/45

**Comment by dako314** [comment]
Gruppenname: Team-314
Direktlink zum Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/46

**Comment by marcelherd** [comment]
Gruppenname: Das beste Team
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/47

**Comment by erikmartens** [comment]
Gruppenname: Salty
Direktlink zum Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/48
Direktlink zu NWJS Builds: https://www.dropbox.com/sh/4sm6j3e166iraok/AAC6PK9uNiJe2J23KXreERyQa?dl=0

**Comment by FriederikeHerbold** [comment]
Gruppenname: Team Mystic
Direktlink zum Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/49

**Comment by limecakeio** [comment]
Gruppenname: ForkGitIT
Direktlink zum Pull-Request inklusive NWJS Bundles: https://github.com/INT-WAW/Boilerplate/pull/50

**Comment by freakdran** [comment]
Gruppenname: Manatees
Direktlink: [INT-WAW/Boilerplate#52](https://github.com/INT-WAW/Boilerplate/pull/52)

**Comment by Lucas964** [comment]
Gruppenname: Boosted Apes
Link zum Pullrequest: https://github.com/INT-WAW/Boilerplate/pull/53

**Comment by Dragashi** [comment]
Gruppenname: ERROR404
Link zum Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/54

**Comment by cookiengineer** [comment]
Noch mal fuer alle. Wenn ihr eslint durchlaufen laesst und es einfach komplett ignoriert gibt es nen krassen Punkteabzug. Ich erwarte dass der Code linted und lesbar ist. Fixt das bis nachher, sonst gibts nen krassen Punkteabzug.

**Comment by erikmartens** [comment]
Was ist mit Fehlern wie "getData() is not defined", einfach weil die Funktion in einem anderen .js Dokument definiert ist? Oder "$ is not defined", weil eslint jQuery nicht kennt? Der Rest ist gefixt

**Comment by cookiengineer** [comment]
Einzelne Fehler mit globalen variablen lasse ich gelten und ignoriere ich, diese koenntet ihr in der eslintrc eintragen als globals. In deinem Fall muesstest du bei den globals ein `$` hinzufuegen.

Ich habe das noch mal explizit erwaehnt, weil hier einige 400+ Fehler mit  eslint haben. Deren Code laeuft nicht, weil undefinierte variablen verwendet werden. Das ALLES kann man sich sparen mit nur einem effing eslint run.

**Comment by erikmartens** [comment]
Alles klar. Wir werden $ dann noch hinzufügen. Danke für die Antwort.

**Comment by FriederikeHerbold** [comment]
was ist mit "Unexpected tab character" obwohl die tabs via --fix eingefügt wurden

**Comment by cookiengineer** [comment]
@FriederikeHerbold Wird wahrscheinlich so etwas wie `}\telse{` sein, was bei einigen schon vor kam. Das darf nicht sein.

**Comment by cookiengineer** [comment]
Alle Gruppen die noch nen :-1: als Reaktion haben, haben noch eslint Probleme und/oder Code Logik Probleme, die mit eslint aufgedeckt werden.

Hinweis ist, dass jede eslint Meldung ihren Sinn hat und einfach behoben werden kann. Typische Probleme sind nicht definierte Variablen, die mit let/const behoben waeren.
