### ISSUE TITLE
Ausweich-Vorlesung am 08. November

### ISSUE THREAD

**Issue by cookiengineer** [INT-WAW/Slides#3]
Die naechste Vorlesung findet am 04. November statt, gleicher Raum, gleiche Hochschule.
Termin ist:

**Dienstag, 08. November 2016 13:40 - 16:50 Uhr**

**Treffpunkt: Raum A/107**

TODO fuer @cookiengineer
- [x] Sekretariat Bescheid geben warum Raumplan fehlt
- [ ] Keycard fuer ~~008~~ A/107 organisieren
- [ ] Potenzieller Ausweichplan ist Mo, Mi, Do 1. Stunde (8:00 Uhr)

**Comment by Tuekol** [comment]
Hat sich geändert. Der Ersatztermin findet am Dienstag, den 8. November, statt. Uhrzeit und Ort bleibt gleich.

**Comment by cookiengineer** [comment]
Habe den Raum heute vom Sekretariat bestaetigt bekommen. Am Dienstag haben wir, da A/008 belegt ist, im Raum A/107 Unterricht. Gleiche Uhrzeit, also **Dienstag, 08.11. um 13:30 Uhr in A/107**.

Bitte bringt eure Keycard mit, damit wir in den Raum kommen :tada:
