### ISSUE TITLE
Testat Verschoben

### ISSUE THREAD

**Issue by FriederikeHerbold** [INT-WAW/Slides#5]
Sie haben entschieden am 16.11.2016 noch einmal Projektarbeit zu machen.
Ist das Testat dann wie erwartet am 23.11.2016?
Wann genau ist dann der Pull-Request fällig?
Könnten sie dann auch den anderen Issue Ändern?

Danke 

Friederike

**Comment by cookiengineer** [comment]
Issue #4 wurde angepasst. Testat um eine Woche verschoben. Naechste Woche ist wieder Projektarbeit  🎉
