### ISSUE TITLE
Must-Watch Resources

### ISSUE THREAD

**Issue by cookiengineer** [INT-WAW/Slides#7]
A list of further resources about JS development, debugging etc.:

- [Chrome Debugging 101](https://www.youtube.com/watch?v=HF1luRD4Qmk)

**Comment by marcelherd** [comment]
https://github.com/sindresorhus/awesome
https://github.com/getify/You-Dont-Know-JS
https://github.com/ericelliott/essential-javascript-links
https://github.com/alex/what-happens-when

[/r/webdev+web_design+programming+javascript+node](https://www.reddit.com/r/webdev+web_design+programming+javascript+node)
[Hacker News](https://news.ycombinator.com/)

https://laracasts.com

**Comment by cookiengineer** [comment]
- [/r/coding](https://www.reddit.com/r/coding) is also one of my favorites.

(Best of) funfunfunction's Youtube Channel:

- [Higher-order functions](https://www.youtube.com/watch?v=BMUiFMZr7vk)
- [var, let and const](https://www.youtube.com/watch?v=sjyJBL5fkp8)
- [bind and this](https://www.youtube.com/watch?v=GhbhD1HR5vk)
- [bind and this p2](https://www.youtube.com/watch?v=PIkA60I0dKU)
- [Composite Pattern over Inheritance](https://www.youtube.com/watch?v=wfMtDGfHWpA)
- [Arrow Functions](https://www.youtube.com/watch?v=6sQDTgOqh-I)
- [Function Generators](https://www.youtube.com/watch?v=ategZqxHkz4)

**Comment by marcelherd** [comment]
[Overview of ES6 features](http://adrianmejia.com/blog/2016/10/19/Overview-of-JavaScript-ES6-features-a-k-a-ECMAScript-6-and-ES2015/#.WA4G-3dZebs.hackernews)

**Comment by cookiengineer** [comment]
Bezueglich ES6: Dadurch dass viele von euch noch mit nem uralten Browser rumgurken habe ich ne Alternative zu ES6-Shim and the like gebaut; ist aber noch nich ganz fertig bezueglich Web Components und CSS4: https://polyfillr.github.io/

**Comment by cookiengineer** [comment]
Best thread of the whole internet: https://www.reddit.com/r/AskReddit/comments/5fb9n7/what_are_some_awesome_websites_that_not_enough/
