### ISSUE TITLE
Botnet Tasks

### ISSUE THREAD

**Issue by freakdran** [INT-WAW/Slides#8]
Die Tasks sind im Moment ziemlich vollgeklatscht, sprich 650+ Einträge. Löscht du die irgendwann? 

Bzw falls es so viele sind, soll dann die section doch scrollbar sein, damit man bei der Tabelle auch ans Ende kommt?

**Comment by cookiengineer** [comment]
> Löscht du die irgendwann?

Ja.

> Bzw falls es so viele sind, soll dann die section doch scrollbar sein, damit man bei der Tabelle auch ans Ende kommt?

Ja.

**Comment by freakdran** [comment]
![grund](https://cloud.githubusercontent.com/assets/22498577/20313882/9b3f53c2-ab58-11e6-8ede-77f97e91fd93.png)
Ich glaub ich weis warum Tasks so voll ist..
