### ISSUE TITLE
HTML/JS Injection

### ISSUE THREAD

**Issue by dako314** [INT-WAW/Slides#9]
Hi @cookiengineer ,

ich habe ein wenig mit HTML/JS Injection rumgespielt, um zu testen, ob meine Seite sicher dagegen ist.

Also habe ich folgende Codes in die API/Tasks eingefügt:

`{
		"id": 882,
		"type": "hash-md5",
		"data": {
			"input": "<script>alert(\"hello\");</script>",
			"output": null
		}
	},
	{
		"id": 883,
		"type": "hash-md5",
		"data": {
			"input": "<script>while(true) {}</script>",
			"output": null
		}
	},
	{
		"id": 884,
		"type": "hash-md5",
		"data": {
			"input": "<script>alert(„hello“); </script>",
			"output": null
		}
	},`

Bei mir hat das auch super funktioniert, nur jetzt habe ich bemerkt, dass bei anderen Gruppen die Seite abkackt, da das Alert ausgegeben wird und die while-true-Schleife ausgeführt wird :) - scheinbar hat jemand jQuery benutzt und html() statt text() für das Einfügen genutzt ;)

Kannst du die IDs 882, 883 und 884 bitte raus löschen?

Viele Grüße
Daniel Koch

**Comment by h4ck-rOOt** [comment]
Du beschreibst hier einen Injection-Angriff, der nicht von einem Client abgefangen (escaped) werden sollte, sondern vom Server (API) selbst.

Diesen "Fehler" einem Client in die Schuhe zu schieben, ist nicht gerade die feine englische Art. Escaping von HTML, sowie Scripts, sollte bereits bei Eingabe in die API abgefangen werden, da niemals Eingaben unvalidiert weiterverarbeiten werden sollen.

Dennoch gebe ich dir Recht, dass man diesen Fehler mit .text() an bestimmten Stellen vermeiden könnte. Der Fehler kann aber auch mit einem document.write() auftreten oder durch Nutzung von anderen Methoden, nicht nur wegen jQuery. Eigentlich hat dies in dem Kontext (Übungen) nicht so wirklich was zu suchen, aber gut die Auswirkungen, von nicht validierten Eingaben, zu sehen.

**Comment by cookiengineer** [comment]
> Du beschreibst hier einen Injection-Angriff, der nicht nur von einem Client abgefangen (escaped) werden sollte, sondern auch vom Server (API) selbst.

Technically, no. Wir bauen eine Rainbow-Table auf, und es sind alle Sonderzeichen fuer Kennwoerter erlaubt. Kennwoerter koennen auch ein "<" und ">" enthalten. Kein Text wird gefiltert und auch Unicode Zeichen jenseits der Emoji und Arab-Section sind erlaubt und serverseitig escaped.

Der Server ist von XSS injection unberuehrt, also ist es definitiv Aufgabe der Clients, ein potenzielles eval() jeglicher Art zu vermeiden.

@dako314 Ich werde das in der naechsten Vorlesung zum Thema Server && node.js ansprechen, dass eure Webanwendung XSS anfaellig ist und entsprechende Beispiele mit einbauen. Habe aber vorerst die DB resetted.

**Comment by h4ck-rOOt** [comment]
Gut, die Aufgabenstellung war mir nicht ganz bekannt, jedoch sollte, je nach Aufgabenstellung, nicht nur auf Seiten des Browsers eine Überprüfung stattfinden.

Input Sanitizing ist ein großes Thema auf beiden Seiten. Klar muss eine clientseitige Anwendung solche Dinge erkennen und präventive Maßnahmen ergreifen, da gebe ich dir voll und ganz Recht.

Es ist schön einige Leute bereits auf diesem Niveau zu sehen, aber findet ihr nicht, dass diese Aufgabenstellungen eher in anderen Vorlesungen thematisiert werden sollten? 

OWASP gibt gute Empfehlungen dazu raus, aber ich würde dies als weiterführendes Thema in Richtung "sichere Internetdienste" für Interessierte behandeln und erstmal sicherstellen, dass die Grundlagen zur DOM-Manipulation von jedem verstanden sind. 

Dies soll keine Wertung über die Wichtigkeit des Themas Sicherheit in Webanwendung sein, sondern lediglich meine persönliche Meinung widerspiegeln.

**Comment by dako314** [comment]
@h4ck-rOOt , @cookiengineer : Vielen Dank eure Informationen. Hat sich damit also erledigt!
